// Top ~200 airports by passenger volume — inline for zero-latency IATA resolution.
// The full dataset (~7,000) is generated by running: pnpm --filter @halite/api airports:fetch
// That script writes apps/api/src/data/airports-full.json which is loaded at runtime if present.

export interface AirportEntry {
  iata: string
  name: string
  city: string
  country: string
  countryCode: string
  lat: number
  lng: number
  timezone: string
}

export const AIRPORTS_INLINE: AirportEntry[] = [
  { iata: 'ATL', name: 'Hartsfield–Jackson Atlanta', city: 'Atlanta', country: 'United States', countryCode: 'US', lat: 33.6407, lng: -84.4277, timezone: 'America/New_York' },
  { iata: 'DFW', name: 'Dallas/Fort Worth International', city: 'Dallas', country: 'United States', countryCode: 'US', lat: 32.8998, lng: -97.0403, timezone: 'America/Chicago' },
  { iata: 'DEN', name: 'Denver International', city: 'Denver', country: 'United States', countryCode: 'US', lat: 39.8561, lng: -104.6737, timezone: 'America/Denver' },
  { iata: 'ORD', name: "O'Hare International", city: 'Chicago', country: 'United States', countryCode: 'US', lat: 41.9742, lng: -87.9073, timezone: 'America/Chicago' },
  { iata: 'MDW', name: 'Chicago Midway', city: 'Chicago', country: 'United States', countryCode: 'US', lat: 41.7868, lng: -87.7522, timezone: 'America/Chicago' },
  { iata: 'LAX', name: 'Los Angeles International', city: 'Los Angeles', country: 'United States', countryCode: 'US', lat: 33.9425, lng: -118.4081, timezone: 'America/Los_Angeles' },
  { iata: 'JFK', name: 'John F. Kennedy International', city: 'New York City', country: 'United States', countryCode: 'US', lat: 40.6413, lng: -73.7781, timezone: 'America/New_York' },
  { iata: 'LGA', name: 'LaGuardia', city: 'New York City', country: 'United States', countryCode: 'US', lat: 40.7769, lng: -73.8740, timezone: 'America/New_York' },
  { iata: 'EWR', name: 'Newark Liberty International', city: 'Newark', country: 'United States', countryCode: 'US', lat: 40.6895, lng: -74.1745, timezone: 'America/New_York' },
  { iata: 'SFO', name: 'San Francisco International', city: 'San Francisco', country: 'United States', countryCode: 'US', lat: 37.6213, lng: -122.3790, timezone: 'America/Los_Angeles' },
  { iata: 'SEA', name: 'Seattle-Tacoma International', city: 'Seattle', country: 'United States', countryCode: 'US', lat: 47.4502, lng: -122.3088, timezone: 'America/Los_Angeles' },
  { iata: 'LAS', name: 'Harry Reid International', city: 'Las Vegas', country: 'United States', countryCode: 'US', lat: 36.0840, lng: -115.1537, timezone: 'America/Los_Angeles' },
  { iata: 'MCO', name: 'Orlando International', city: 'Orlando', country: 'United States', countryCode: 'US', lat: 28.4312, lng: -81.3081, timezone: 'America/New_York' },
  { iata: 'MIA', name: 'Miami International', city: 'Miami', country: 'United States', countryCode: 'US', lat: 25.7959, lng: -80.2870, timezone: 'America/New_York' },
  { iata: 'FLL', name: 'Fort Lauderdale-Hollywood International', city: 'Fort Lauderdale', country: 'United States', countryCode: 'US', lat: 26.0726, lng: -80.1527, timezone: 'America/New_York' },
  { iata: 'CLT', name: 'Charlotte Douglas International', city: 'Charlotte', country: 'United States', countryCode: 'US', lat: 35.2140, lng: -80.9431, timezone: 'America/New_York' },
  { iata: 'PHX', name: 'Phoenix Sky Harbor International', city: 'Phoenix', country: 'United States', countryCode: 'US', lat: 33.4373, lng: -112.0078, timezone: 'America/Phoenix' },
  { iata: 'IAH', name: 'George Bush Intercontinental', city: 'Houston', country: 'United States', countryCode: 'US', lat: 29.9902, lng: -95.3368, timezone: 'America/Chicago' },
  { iata: 'HOU', name: 'William P. Hobby Airport', city: 'Houston', country: 'United States', countryCode: 'US', lat: 29.6454, lng: -95.2789, timezone: 'America/Chicago' },
  { iata: 'BOS', name: 'Logan International', city: 'Boston', country: 'United States', countryCode: 'US', lat: 42.3656, lng: -71.0096, timezone: 'America/New_York' },
  { iata: 'MSP', name: 'Minneapolis-Saint Paul International', city: 'Minneapolis', country: 'United States', countryCode: 'US', lat: 44.8848, lng: -93.2223, timezone: 'America/Chicago' },
  { iata: 'DTW', name: 'Detroit Metropolitan Wayne County', city: 'Detroit', country: 'United States', countryCode: 'US', lat: 42.2162, lng: -83.3554, timezone: 'America/Detroit' },
  { iata: 'PHL', name: 'Philadelphia International', city: 'Philadelphia', country: 'United States', countryCode: 'US', lat: 39.8744, lng: -75.2424, timezone: 'America/New_York' },
  { iata: 'DCA', name: 'Ronald Reagan Washington National', city: 'Washington D.C.', country: 'United States', countryCode: 'US', lat: 38.8521, lng: -77.0377, timezone: 'America/New_York' },
  { iata: 'IAD', name: 'Washington Dulles International', city: 'Washington D.C.', country: 'United States', countryCode: 'US', lat: 38.9531, lng: -77.4565, timezone: 'America/New_York' },
  { iata: 'BWI', name: 'Baltimore/Washington International', city: 'Baltimore', country: 'United States', countryCode: 'US', lat: 39.1754, lng: -76.6684, timezone: 'America/New_York' },
  { iata: 'SAN', name: 'San Diego International', city: 'San Diego', country: 'United States', countryCode: 'US', lat: 32.7338, lng: -117.1933, timezone: 'America/Los_Angeles' },
  { iata: 'TPA', name: 'Tampa International', city: 'Tampa', country: 'United States', countryCode: 'US', lat: 27.9755, lng: -82.5332, timezone: 'America/New_York' },
  { iata: 'PDX', name: 'Portland International', city: 'Portland', country: 'United States', countryCode: 'US', lat: 45.5887, lng: -122.5975, timezone: 'America/Los_Angeles' },
  { iata: 'STL', name: 'St. Louis Lambert International', city: 'St. Louis', country: 'United States', countryCode: 'US', lat: 38.7487, lng: -90.3700, timezone: 'America/Chicago' },
  { iata: 'HNL', name: 'Daniel K. Inouye International', city: 'Honolulu', country: 'United States', countryCode: 'US', lat: 21.3187, lng: -157.9224, timezone: 'Pacific/Honolulu' },
  { iata: 'AUS', name: 'Austin-Bergstrom International', city: 'Austin', country: 'United States', countryCode: 'US', lat: 30.1975, lng: -97.6664, timezone: 'America/Chicago' },
  { iata: 'BNA', name: 'Nashville International', city: 'Nashville', country: 'United States', countryCode: 'US', lat: 36.1245, lng: -86.6782, timezone: 'America/Chicago' },
  { iata: 'SLC', name: 'Salt Lake City International', city: 'Salt Lake City', country: 'United States', countryCode: 'US', lat: 40.7899, lng: -111.9791, timezone: 'America/Denver' },
  { iata: 'RDU', name: 'Raleigh-Durham International', city: 'Raleigh', country: 'United States', countryCode: 'US', lat: 35.8776, lng: -78.7875, timezone: 'America/New_York' },

  // ── Canada ─────────────────────────────────────────────────────────
  { iata: 'YYZ', name: 'Toronto Pearson International', city: 'Toronto', country: 'Canada', countryCode: 'CA', lat: 43.6777, lng: -79.6248, timezone: 'America/Toronto' },
  { iata: 'YVR', name: 'Vancouver International', city: 'Vancouver', country: 'Canada', countryCode: 'CA', lat: 49.1967, lng: -123.1815, timezone: 'America/Vancouver' },
  { iata: 'YUL', name: 'Montréal–Trudeau International', city: 'Montreal', country: 'Canada', countryCode: 'CA', lat: 45.4706, lng: -73.7408, timezone: 'America/Toronto' },
  { iata: 'YYC', name: 'Calgary International', city: 'Calgary', country: 'Canada', countryCode: 'CA', lat: 51.1315, lng: -114.0106, timezone: 'America/Edmonton' },
  { iata: 'YEG', name: 'Edmonton International', city: 'Edmonton', country: 'Canada', countryCode: 'CA', lat: 53.3097, lng: -113.5797, timezone: 'America/Edmonton' },
  { iata: 'YOW', name: 'Ottawa Macdonald–Cartier International', city: 'Ottawa', country: 'Canada', countryCode: 'CA', lat: 45.3225, lng: -75.6692, timezone: 'America/Toronto' },

  // ── United Kingdom ─────────────────────────────────────────────────
  { iata: 'LHR', name: 'Heathrow', city: 'London', country: 'United Kingdom', countryCode: 'GB', lat: 51.4775, lng: -0.4614, timezone: 'Europe/London' },
  { iata: 'LGW', name: 'Gatwick', city: 'London', country: 'United Kingdom', countryCode: 'GB', lat: 51.1537, lng: -0.1821, timezone: 'Europe/London' },
  { iata: 'STN', name: 'Stansted', city: 'London', country: 'United Kingdom', countryCode: 'GB', lat: 51.8850, lng: 0.2350, timezone: 'Europe/London' },
  { iata: 'MAN', name: 'Manchester', city: 'Manchester', country: 'United Kingdom', countryCode: 'GB', lat: 53.3537, lng: -2.2750, timezone: 'Europe/London' },
  { iata: 'EDI', name: 'Edinburgh', city: 'Edinburgh', country: 'United Kingdom', countryCode: 'GB', lat: 55.9500, lng: -3.3725, timezone: 'Europe/London' },
  { iata: 'BHX', name: 'Birmingham', city: 'Birmingham', country: 'United Kingdom', countryCode: 'GB', lat: 52.4539, lng: -1.7480, timezone: 'Europe/London' },

  // ── Europe ─────────────────────────────────────────────────────────
  { iata: 'CDG', name: 'Charles de Gaulle', city: 'Paris', country: 'France', countryCode: 'FR', lat: 49.0097, lng: 2.5479, timezone: 'Europe/Paris' },
  { iata: 'ORY', name: 'Paris Orly', city: 'Paris', country: 'France', countryCode: 'FR', lat: 48.7233, lng: 2.3794, timezone: 'Europe/Paris' },
  { iata: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam', country: 'Netherlands', countryCode: 'NL', lat: 52.3086, lng: 4.7639, timezone: 'Europe/Amsterdam' },
  { iata: 'FRA', name: 'Frankfurt am Main', city: 'Frankfurt', country: 'Germany', countryCode: 'DE', lat: 50.0379, lng: 8.5622, timezone: 'Europe/Berlin' },
  { iata: 'MUC', name: 'Munich', city: 'Munich', country: 'Germany', countryCode: 'DE', lat: 48.3538, lng: 11.7861, timezone: 'Europe/Berlin' },
  { iata: 'TXL', name: 'Berlin Tegel', city: 'Berlin', country: 'Germany', countryCode: 'DE', lat: 52.5597, lng: 13.2877, timezone: 'Europe/Berlin' },
  { iata: 'BER', name: 'Berlin Brandenburg', city: 'Berlin', country: 'Germany', countryCode: 'DE', lat: 52.3667, lng: 13.5033, timezone: 'Europe/Berlin' },
  { iata: 'MAD', name: 'Adolfo Suárez Madrid–Barajas', city: 'Madrid', country: 'Spain', countryCode: 'ES', lat: 40.4719, lng: -3.5626, timezone: 'Europe/Madrid' },
  { iata: 'BCN', name: 'Josep Tarradellas Barcelona–El Prat', city: 'Barcelona', country: 'Spain', countryCode: 'ES', lat: 41.2971, lng: 2.0785, timezone: 'Europe/Madrid' },
  { iata: 'FCO', name: 'Leonardo da Vinci–Fiumicino', city: 'Rome', country: 'Italy', countryCode: 'IT', lat: 41.8003, lng: 12.2389, timezone: 'Europe/Rome' },
  { iata: 'MXP', name: 'Milan Malpensa', city: 'Milan', country: 'Italy', countryCode: 'IT', lat: 45.6306, lng: 8.7281, timezone: 'Europe/Rome' },
  { iata: 'ZRH', name: 'Zurich', city: 'Zurich', country: 'Switzerland', countryCode: 'CH', lat: 47.4647, lng: 8.5492, timezone: 'Europe/Zurich' },
  { iata: 'VIE', name: 'Vienna International', city: 'Vienna', country: 'Austria', countryCode: 'AT', lat: 48.1103, lng: 16.5697, timezone: 'Europe/Vienna' },
  { iata: 'BRU', name: 'Brussels', city: 'Brussels', country: 'Belgium', countryCode: 'BE', lat: 50.9014, lng: 4.4844, timezone: 'Europe/Brussels' },
  { iata: 'CPH', name: 'Copenhagen', city: 'Copenhagen', country: 'Denmark', countryCode: 'DK', lat: 55.6179, lng: 12.6560, timezone: 'Europe/Copenhagen' },
  { iata: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm', country: 'Sweden', countryCode: 'SE', lat: 59.6519, lng: 17.9186, timezone: 'Europe/Stockholm' },
  { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki', country: 'Finland', countryCode: 'FI', lat: 60.3172, lng: 24.9633, timezone: 'Europe/Helsinki' },
  { iata: 'OSL', name: 'Oslo Gardermoen', city: 'Oslo', country: 'Norway', countryCode: 'NO', lat: 60.1939, lng: 11.1004, timezone: 'Europe/Oslo' },
  { iata: 'IST', name: 'Istanbul', city: 'Istanbul', country: 'Turkey', countryCode: 'TR', lat: 41.2606, lng: 28.7425, timezone: 'Europe/Istanbul' },
  { iata: 'SAW', name: 'Sabiha Gökçen International', city: 'Istanbul', country: 'Turkey', countryCode: 'TR', lat: 40.8986, lng: 29.3092, timezone: 'Europe/Istanbul' },
  { iata: 'WAW', name: 'Warsaw Chopin', city: 'Warsaw', country: 'Poland', countryCode: 'PL', lat: 52.1657, lng: 20.9671, timezone: 'Europe/Warsaw' },
  { iata: 'PRG', name: 'Václav Havel Prague', city: 'Prague', country: 'Czech Republic', countryCode: 'CZ', lat: 50.1008, lng: 14.2600, timezone: 'Europe/Prague' },
  { iata: 'BUD', name: 'Budapest Ferenc Liszt', city: 'Budapest', country: 'Hungary', countryCode: 'HU', lat: 47.4298, lng: 19.2611, timezone: 'Europe/Budapest' },
  { iata: 'OTP', name: 'Henri Coandă Bucharest', city: 'Bucharest', country: 'Romania', countryCode: 'RO', lat: 44.5711, lng: 26.0858, timezone: 'Europe/Bucharest' },
  { iata: 'ATH', name: 'Athens Eleftherios Venizelos', city: 'Athens', country: 'Greece', countryCode: 'GR', lat: 37.9364, lng: 23.9445, timezone: 'Europe/Athens' },
  { iata: 'LIS', name: 'Humberto Delgado Lisbon', city: 'Lisbon', country: 'Portugal', countryCode: 'PT', lat: 38.7756, lng: -9.1354, timezone: 'Europe/Lisbon' },

  // ── Middle East ────────────────────────────────────────────────────
  { iata: 'DXB', name: 'Dubai International', city: 'Dubai', country: 'United Arab Emirates', countryCode: 'AE', lat: 25.2532, lng: 55.3657, timezone: 'Asia/Dubai' },
  { iata: 'AUH', name: 'Abu Dhabi International', city: 'Abu Dhabi', country: 'United Arab Emirates', countryCode: 'AE', lat: 24.4330, lng: 54.6511, timezone: 'Asia/Dubai' },
  { iata: 'DOH', name: 'Hamad International', city: 'Doha', country: 'Qatar', countryCode: 'QA', lat: 25.2609, lng: 51.6138, timezone: 'Asia/Qatar' },
  { iata: 'RUH', name: 'King Khalid International', city: 'Riyadh', country: 'Saudi Arabia', countryCode: 'SA', lat: 24.9576, lng: 46.6988, timezone: 'Asia/Riyadh' },
  { iata: 'JED', name: 'King Abdulaziz International', city: 'Jeddah', country: 'Saudi Arabia', countryCode: 'SA', lat: 21.6796, lng: 39.1565, timezone: 'Asia/Riyadh' },
  { iata: 'KWI', name: 'Kuwait International', city: 'Kuwait City', country: 'Kuwait', countryCode: 'KW', lat: 29.2267, lng: 47.9689, timezone: 'Asia/Kuwait' },
  { iata: 'BEY', name: 'Beirut Rafic Hariri International', city: 'Beirut', country: 'Lebanon', countryCode: 'LB', lat: 33.8209, lng: 35.4884, timezone: 'Asia/Beirut' },
  { iata: 'AMM', name: 'Queen Alia International', city: 'Amman', country: 'Jordan', countryCode: 'JO', lat: 31.7226, lng: 35.9932, timezone: 'Asia/Amman' },
  { iata: 'TLV', name: 'Ben Gurion International', city: 'Tel Aviv', country: 'Israel', countryCode: 'IL', lat: 32.0114, lng: 34.8867, timezone: 'Asia/Jerusalem' },
  { iata: 'CAI', name: 'Cairo International', city: 'Cairo', country: 'Egypt', countryCode: 'EG', lat: 30.1219, lng: 31.4056, timezone: 'Africa/Cairo' },

  // ── Africa ─────────────────────────────────────────────────────────
  { iata: 'LOS', name: 'Murtala Muhammed International', city: 'Lagos', country: 'Nigeria', countryCode: 'NG', lat: 6.5774, lng: 3.3212, timezone: 'Africa/Lagos' },
  { iata: 'ABV', name: 'Nnamdi Azikiwe International', city: 'Abuja', country: 'Nigeria', countryCode: 'NG', lat: 9.0068, lng: 7.2632, timezone: 'Africa/Lagos' },
  { iata: 'JNB', name: 'O.R. Tambo International', city: 'Johannesburg', country: 'South Africa', countryCode: 'ZA', lat: -26.1367, lng: 28.2411, timezone: 'Africa/Johannesburg' },
  { iata: 'CPT', name: 'Cape Town International', city: 'Cape Town', country: 'South Africa', countryCode: 'ZA', lat: -33.9648, lng: 18.6017, timezone: 'Africa/Johannesburg' },
  { iata: 'NBO', name: 'Jomo Kenyatta International', city: 'Nairobi', country: 'Kenya', countryCode: 'KE', lat: -1.3192, lng: 36.9275, timezone: 'Africa/Nairobi' },
  { iata: 'ACC', name: 'Kotoka International', city: 'Accra', country: 'Ghana', countryCode: 'GH', lat: 5.6052, lng: -0.1668, timezone: 'Africa/Accra' },
  { iata: 'ABJ', name: 'Félix-Houphouët-Boigny International', city: 'Abidjan', country: "Côte d'Ivoire", countryCode: 'CI', lat: 5.2613, lng: -3.9263, timezone: 'Africa/Abidjan' },
  { iata: 'DKR', name: 'Léopold Sédar Senghor International', city: 'Dakar', country: 'Senegal', countryCode: 'SN', lat: 14.7397, lng: -17.4902, timezone: 'Africa/Dakar' },
  { iata: 'ADD', name: 'Addis Ababa Bole International', city: 'Addis Ababa', country: 'Ethiopia', countryCode: 'ET', lat: 8.9779, lng: 38.7993, timezone: 'Africa/Addis_Ababa' },
  { iata: 'CMN', name: 'Mohammed V International', city: 'Casablanca', country: 'Morocco', countryCode: 'MA', lat: 33.3675, lng: -7.5898, timezone: 'Africa/Casablanca' },
  { iata: 'ALG', name: 'Houari Boumediene', city: 'Algiers', country: 'Algeria', countryCode: 'DZ', lat: 36.6910, lng: 3.2154, timezone: 'Africa/Algiers' },
  { iata: 'DLA', name: 'Douala International', city: 'Douala', country: 'Cameroon', countryCode: 'CM', lat: 4.0061, lng: 9.7197, timezone: 'Africa/Douala' },
  { iata: 'DAR', name: 'Julius Nyerere International', city: 'Dar es Salaam', country: 'Tanzania', countryCode: 'TZ', lat: -6.8781, lng: 39.2026, timezone: 'Africa/Dar_es_Salaam' },
  { iata: 'EBB', name: 'Entebbe International', city: 'Kampala', country: 'Uganda', countryCode: 'UG', lat: 0.0424, lng: 32.4435, timezone: 'Africa/Kampala' },

  // ── Asia ────────────────────────────────────────────────────────────
  { iata: 'HND', name: 'Tokyo Haneda', city: 'Tokyo', country: 'Japan', countryCode: 'JP', lat: 35.5494, lng: 139.7798, timezone: 'Asia/Tokyo' },
  { iata: 'NRT', name: 'Narita International', city: 'Tokyo', country: 'Japan', countryCode: 'JP', lat: 35.7720, lng: 140.3929, timezone: 'Asia/Tokyo' },
  { iata: 'ICN', name: 'Incheon International', city: 'Seoul', country: 'South Korea', countryCode: 'KR', lat: 37.4691, lng: 126.4505, timezone: 'Asia/Seoul' },
  { iata: 'PEK', name: 'Beijing Capital International', city: 'Beijing', country: 'China', countryCode: 'CN', lat: 40.0799, lng: 116.6031, timezone: 'Asia/Shanghai' },
  { iata: 'PKX', name: 'Beijing Daxing International', city: 'Beijing', country: 'China', countryCode: 'CN', lat: 39.5098, lng: 116.4105, timezone: 'Asia/Shanghai' },
  { iata: 'PVG', name: 'Shanghai Pudong International', city: 'Shanghai', country: 'China', countryCode: 'CN', lat: 31.1443, lng: 121.8083, timezone: 'Asia/Shanghai' },
  { iata: 'SHA', name: 'Shanghai Hongqiao International', city: 'Shanghai', country: 'China', countryCode: 'CN', lat: 31.1979, lng: 121.3364, timezone: 'Asia/Shanghai' },
  { iata: 'HKG', name: 'Hong Kong International', city: 'Hong Kong', country: 'Hong Kong', countryCode: 'HK', lat: 22.3080, lng: 113.9185, timezone: 'Asia/Hong_Kong' },
  { iata: 'SIN', name: 'Singapore Changi', city: 'Singapore', country: 'Singapore', countryCode: 'SG', lat: 1.3644, lng: 103.9915, timezone: 'Asia/Singapore' },
  { iata: 'BOM', name: 'Chhatrapati Shivaji Maharaj International', city: 'Mumbai', country: 'India', countryCode: 'IN', lat: 19.0896, lng: 72.8656, timezone: 'Asia/Kolkata' },
  { iata: 'DEL', name: 'Indira Gandhi International', city: 'New Delhi', country: 'India', countryCode: 'IN', lat: 28.5562, lng: 77.1000, timezone: 'Asia/Kolkata' },
  { iata: 'BLR', name: 'Kempegowda International', city: 'Bangalore', country: 'India', countryCode: 'IN', lat: 13.1986, lng: 77.7066, timezone: 'Asia/Kolkata' },
  { iata: 'MAA', name: 'Chennai International', city: 'Chennai', country: 'India', countryCode: 'IN', lat: 12.9900, lng: 80.1693, timezone: 'Asia/Kolkata' },
  { iata: 'CCU', name: 'Netaji Subhas Chandra Bose International', city: 'Kolkata', country: 'India', countryCode: 'IN', lat: 22.6520, lng: 88.4463, timezone: 'Asia/Kolkata' },
  { iata: 'CGK', name: 'Soekarno-Hatta International', city: 'Jakarta', country: 'Indonesia', countryCode: 'ID', lat: -6.1256, lng: 106.6558, timezone: 'Asia/Jakarta' },
  { iata: 'KUL', name: 'Kuala Lumpur International', city: 'Kuala Lumpur', country: 'Malaysia', countryCode: 'MY', lat: 2.7456, lng: 101.7099, timezone: 'Asia/Kuala_Lumpur' },
  { iata: 'BKK', name: 'Suvarnabhumi', city: 'Bangkok', country: 'Thailand', countryCode: 'TH', lat: 13.6900, lng: 100.7501, timezone: 'Asia/Bangkok' },
  { iata: 'MNL', name: 'Ninoy Aquino International', city: 'Manila', country: 'Philippines', countryCode: 'PH', lat: 14.5086, lng: 121.0197, timezone: 'Asia/Manila' },
  { iata: 'SGN', name: 'Tan Son Nhat International', city: 'Ho Chi Minh City', country: 'Vietnam', countryCode: 'VN', lat: 10.8188, lng: 106.6520, timezone: 'Asia/Ho_Chi_Minh' },
  { iata: 'HAN', name: 'Noi Bai International', city: 'Hanoi', country: 'Vietnam', countryCode: 'VN', lat: 21.2212, lng: 105.8072, timezone: 'Asia/Ho_Chi_Minh' },
  { iata: 'DAD', name: 'Da Nang International', city: 'Da Nang', country: 'Vietnam', countryCode: 'VN', lat: 16.0439, lng: 108.1992, timezone: 'Asia/Ho_Chi_Minh' },
  { iata: 'TPE', name: 'Taiwan Taoyuan International', city: 'Taipei', country: 'Taiwan', countryCode: 'TW', lat: 25.0777, lng: 121.2326, timezone: 'Asia/Taipei' },
  { iata: 'KHI', name: 'Jinnah International', city: 'Karachi', country: 'Pakistan', countryCode: 'PK', lat: 24.9065, lng: 67.1608, timezone: 'Asia/Karachi' },
  { iata: 'LHE', name: 'Allama Iqbal International', city: 'Lahore', country: 'Pakistan', countryCode: 'PK', lat: 31.5216, lng: 74.4036, timezone: 'Asia/Karachi' },
  { iata: 'DAC', name: 'Hazrat Shahjalal International', city: 'Dhaka', country: 'Bangladesh', countryCode: 'BD', lat: 23.8433, lng: 90.3979, timezone: 'Asia/Dhaka' },
  { iata: 'CMB', name: 'Bandaranaike International', city: 'Colombo', country: 'Sri Lanka', countryCode: 'LK', lat: 7.1808, lng: 79.8841, timezone: 'Asia/Colombo' },

  // ── Latin America ──────────────────────────────────────────────────
  { iata: 'GRU', name: 'São Paulo/Guarulhos International', city: 'São Paulo', country: 'Brazil', countryCode: 'BR', lat: -23.4356, lng: -46.4731, timezone: 'America/Sao_Paulo' },
  { iata: 'CGH', name: 'Congonhas Airport', city: 'São Paulo', country: 'Brazil', countryCode: 'BR', lat: -23.6267, lng: -46.6558, timezone: 'America/Sao_Paulo' },
  { iata: 'GIG', name: 'Rio de Janeiro/Galeão International', city: 'Rio de Janeiro', country: 'Brazil', countryCode: 'BR', lat: -22.8100, lng: -43.2506, timezone: 'America/Sao_Paulo' },
  { iata: 'EZE', name: 'Ministro Pistarini International', city: 'Buenos Aires', country: 'Argentina', countryCode: 'AR', lat: -34.8222, lng: -58.5358, timezone: 'America/Argentina/Buenos_Aires' },
  { iata: 'SCL', name: 'Arturo Merino Benítez International', city: 'Santiago', country: 'Chile', countryCode: 'CL', lat: -33.3930, lng: -70.7858, timezone: 'America/Santiago' },
  { iata: 'BOG', name: 'El Dorado International', city: 'Bogotá', country: 'Colombia', countryCode: 'CO', lat: 4.7016, lng: -74.1469, timezone: 'America/Bogota' },
  { iata: 'LIM', name: 'Jorge Chávez International', city: 'Lima', country: 'Peru', countryCode: 'PE', lat: -12.0219, lng: -77.1143, timezone: 'America/Lima' },
  { iata: 'MEX', name: 'Benito Juárez International', city: 'Mexico City', country: 'Mexico', countryCode: 'MX', lat: 19.4363, lng: -99.0721, timezone: 'America/Mexico_City' },
  { iata: 'CUN', name: 'Cancún International', city: 'Cancún', country: 'Mexico', countryCode: 'MX', lat: 21.0365, lng: -86.8771, timezone: 'America/Cancun' },
  { iata: 'PTY', name: 'Tocumen International', city: 'Panama City', country: 'Panama', countryCode: 'PA', lat: 9.0714, lng: -79.3835, timezone: 'America/Panama' },
  { iata: 'UIO', name: 'Mariscal Sucre International', city: 'Quito', country: 'Ecuador', countryCode: 'EC', lat: -0.1292, lng: -78.3575, timezone: 'America/Guayaquil' },
  { iata: 'KIN', name: 'Norman Manley International', city: 'Kingston', country: 'Jamaica', countryCode: 'JM', lat: 17.9357, lng: -76.7875, timezone: 'America/Jamaica' },
  { iata: 'POS', name: 'Piarco International', city: 'Port of Spain', country: 'Trinidad and Tobago', countryCode: 'TT', lat: 10.5954, lng: -61.3372, timezone: 'America/Port_of_Spain' },

  // ── Oceania ────────────────────────────────────────────────────────
  { iata: 'SYD', name: 'Kingsford Smith', city: 'Sydney', country: 'Australia', countryCode: 'AU', lat: -33.9399, lng: 151.1753, timezone: 'Australia/Sydney' },
  { iata: 'MEL', name: 'Melbourne', city: 'Melbourne', country: 'Australia', countryCode: 'AU', lat: -37.6733, lng: 144.8430, timezone: 'Australia/Melbourne' },
  { iata: 'BNE', name: 'Brisbane', city: 'Brisbane', country: 'Australia', countryCode: 'AU', lat: -27.3842, lng: 153.1175, timezone: 'Australia/Brisbane' },
  { iata: 'PER', name: 'Perth', city: 'Perth', country: 'Australia', countryCode: 'AU', lat: -31.9403, lng: 115.9669, timezone: 'Australia/Perth' },
  { iata: 'ADL', name: 'Adelaide', city: 'Adelaide', country: 'Australia', countryCode: 'AU', lat: -34.9450, lng: 138.5306, timezone: 'Australia/Adelaide' },
  { iata: 'AKL', name: 'Auckland', city: 'Auckland', country: 'New Zealand', countryCode: 'NZ', lat: -37.0082, lng: 174.7917, timezone: 'Pacific/Auckland' },
  { iata: 'CHC', name: 'Christchurch', city: 'Christchurch', country: 'New Zealand', countryCode: 'NZ', lat: -43.4894, lng: 172.5322, timezone: 'Pacific/Auckland' },
]

export const BY_IATA = new Map(AIRPORTS_INLINE.map((a) => [a.iata, a]))
